# Premier pas avec les données Airbnb de Paris

## 1. Chargement des Données

In [20]:
import pandas as pd

# Chargement du fichier 'listings.csv' depuis Google Drive
drive_listings_df = pd.read_csv('/content/drive/MyDrive/[Cours] Collecte&ExplorationData/listings.csv')

# Chargement du fichier 'reviews.csv' depuis Google Drive
drive_reviews_df = pd.read_csv('/content/drive/MyDrive/[Cours] Collecte&ExplorationData/reviews.csv')

## 2. Exploration des Données 'listings'

### 2.1 Aperçu Général du DataFrame `drive_listings_df`

In [21]:
print('\nPremières 5 lignes :')
display(drive_listings_df.head())
print('\nColonnes :')
print(drive_listings_df.columns)
print('\nTaille (lignes, colonnes) :')
print(drive_listings_df.shape)

Premières 5 lignes :

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2719440,https://www.airbnb.com/rooms/2719440,20250912034503,2025-09-12,previous scrape,Nice flat close to Montparnasse,This beautiful apartment is very well located ...,"The neighborhood is very nice, feel free to sh...",https://a0.muscache.com/pictures/295786e7-116c...,13915159,https://www.airbnb.com/users/show/13915159,Thibaut,2014-04-05,"Paris, France","I am living in Paris since 10 years, and I lov...",NaN,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/242c2...,https://a0.muscache.com/im/pictures/user/242c2...,Invalides - Ecole Militaire,1.0,1.0,"['email', 'phone']",t,t,Neighborhood highlights,Palais-Bourbon,NaN,48.849970,2.319740,Entire rental unit,Entire home/apt,2,NaN,1 bath,1.0,NaN,"[""Wifi"", ""Hot water"", ""Heating"", ""Coffee maker...",NaN,2,7,2.0,2.0,7.0,7.0,2.0,7.0,NaN,t,0,0,0,0,2025-09-12,79,0,0,0,0,0,NaN,2014-05-17,2020-03-13,4.78,4.94,4.60,4.91,4.94,4.86,4.73,7510702406383,f,1,1,0,0,0.57
1,2721397,https://www.airbnb.com/rooms/2721397,20250912034503,2025-09-12,previous scrape,"Marais - Charming loft, river view","In the heart of historical Paris le Marais, gr...",Le Marais is the heart of Paris. Few years ago...,https://a0.muscache.com/pictures/de55313f-9b4b...,13925876,https://www.airbnb.com/users/show/13925876,Cecilie,2014-04-05,"Paris, France","I travel a lot for work and when I'm away, my ...",within a few hours,100%,92%,t,https://a0.muscache.com/im/users/13925876/prof...,https://a0.muscache.com/im/users/13925876/prof...,Saint-Paul - Ile Saint-Louis,1.0,1.0,"['email', 'phone']",t,t,Neighborhood highlights,Hôtel-de-Ville,NaN,48.852030,2.361760,Entire rental unit,Entire home/apt,2,NaN,1 bath,1.0,NaN,"[""Paid parking on premises"", ""Wifi"", ""Free was...",NaN,5,6,5.0,5.0,6.0,6.0,5.0,6.0,NaN,t,3,3,3,44,2025-09-12,88,13,1,5,9,135,NaN,2014-10-29,2025-08-29,4.86,4.92,4.77,4.88,4.95,4.91,4.85,7510400455677,f,1,1,0,0,0.66
2,2726092,https://www.airbnb.com/rooms/2726092,20250912034503,2025-09-12,previous scrape,Superbe 2 pièces idéalement placé,A stone's throw from Parc Monceau and the Arc ...,Quiet and residential area... Close to the Bat...,https://a0.muscache.com/pictures/6d6c4bc6-9473...,13612373,https://www.airbnb.com/users/show/13612373,Clemence,2014-03-27,"Paris, France",NaN,NaN,NaN,NaN,f,https://a0.muscache.com/im/users/13612373/prof...,https://a0.muscache.com/im/users/13612373/prof...,Monceau,1.0,1.0,"['email', 'phone']",t,f,Neighborhood highlights,Batignolles-Monceau,NaN,48.880040,2.306860,Entire rental unit,Entire home/apt,4,NaN,1 bath,1.0,NaN,"[""Hair dryer"", ""Iron"", ""TV"", ""Heating"", ""Wifi""...",NaN,365,1125,365.0,365.0,1125.0,1125.0,365.0,1125.0,NaN,t,0,0,0,0,2025-09-12,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
3,2726327,https://www.airbnb.com/rooms/2726327,20250912034503,2025-09-12,previous scrape,"Cozy place, Sacré Coeur Montmartre in the SoPi",Cozy apartment close to everything.<br />Perfe...,One of the most trendy corners of the capital ...,https://a0.muscache.com/pictures/6b569382-aed7...,7483725,https://www.airbnb.com/users/show/7483725,Hélène,2013-07-14,"Paris, France","Jeune ingénieur, je propose mon appartement à ...",within an hour,100%,89%,f,https://a0.muscache.com/im/users/7483725/profi...,https://a0.muscache.com/im/users/7483725/profi...,Pigalle - Saint-Georges,1.0,3.0,"['email', 'phone']",t,t,Neighborhood highlights,Opéra,NaN,48.882710,2.343550,Entire rental unit,Entire home/apt,3,NaN,1 bath,1.0,NaN,"[""Elevator"", ""Hot water kettle"", ""Wifi"", ""Laun...",NaN,3,4,3.0,3.0,4.0,4.0,3.0,4.0,NaN,t,3,5,22,297,2025-09-12,99,8,0,43,14,83,NaN,2014-05-25,2025-07-03,4.81,4.82,4.82,4.92,4.97,4.92,4.67,7510901014972,f,1,1,0,0,0.72
4,2727929,https://www.airbnb.com/rooms/2727929,20250912034503,2025-09-12,previous scrape,Appartement d'architecte - Montmartre,"Our apartment, refurbished by an architect in ...",The apartment is in the heart of Paris's 18th ...,https://a0.muscache.com/pictures/miso/Hosting-...,13960346,https://www.airbnb.com/users/show/13960346,Paul,2014-04-06,"Paris, France",NaN,within an hour,100%,100%,f,https://a0.muscache.com/im/pictures/user/cea46...,https://a0.muscache.com/im/pictures/user/cea46...,Vaugirard,1.0,1.0,"['email', 'phone']",t,t,Neighborhood highlights,Buttes-Montmartre,NaN,48.894917,2.336131,Entire rental unit,Entire home/apt,2,NaN,1 bath,1.0,NaN,"[""Elevator"", ""Wifi"", ""Self check-in"", ""Hot wat...",NaN,2,365,3.0,3.0,1125.0,1125.0,3.0,1125.0,NaN,t,0,10,10,83,2025-09-12,7,1,0,10,2,10,NaN,2023-05-21,2025-07-20,5.00,5.00,5.00,4.71,5.00,4.57,5.00,7511808333770,f,1,1,0,0,0.25

Colonnes :
Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

Taille (lignes, colonnes) :
(81853, 79)

### 2.2 Examen d'un Enregistrement Unique en format paragraphe

In [22]:
# Sélection du premier enregistrement
record = drive_listings_df.iloc[0]

# Formatage de l'enregistrement en paragraphe
formatted_record = []
for column, value in record.items():
    formatted_record.append(f"{column}: {value}")

# Joindre toutes les parties formatées avec un séparateur pour former un paragraphe
paragraph_output = "\n ".join(formatted_record)

print(paragraph_output)

id: 2719440
 listing_url: https://www.airbnb.com/rooms/2719440
 scrape_id: 20250912034503
 last_scraped: 2025-09-12
 source: previous scrape
 name: Nice flat close to Montparnasse
 description: This beautiful apartment is very well located in Paris (5 min walking from Montparnasse). It's fully equipped and it can welcome 2 people (one double bed). You can have some fun cooking or relaxing in the living room. The district is very attractive!
 neighborhood_overview: The neighborhood is very nice, feel free to share a drink with them:-)
 picture_url: https://a0.muscache.com/pictures/295786e7-116c-4c62-b450-b91bffea8eb0.jpg
 host_id: 13915159
 host_url: https://www.airbnb.com/users/show/13915159
 host_name: Thibaut
 host_since: 2014-04-05
 host_location: Paris, France
 host_about: I am living in Paris since 10 years, and I love travelling looking for some new place with new people ! I've been in many different countries and that is why I'd like to share my appartment !
I also like playing music (drum or guitar) or creating electronic music :)

So if you want to be confortable in Paris, contact me. I would be glad to share all lovely uncommon places!
 host_response_time: nan
 host_response_rate: nan
 host_acceptance_rate: nan
 host_is_superhost: f
 host_thumbnail_url: https://a0.muscache.com/im/pictures/user/242c2fc1-d430-46da-a3e8-f22e2e3dca64.jpg?aki_policy=profile_small
 host_picture_url: https://a0.muscache.com/im/pictures/user/242c2fc1-d430-46da-a3e8-f22e2e3dca64.jpg?aki_policy=profile_x_medium
 host_neighbourhood: Invalides - Ecole Militaire
 host_listings_count: 1.0
 host_total_listings_count: 1.0
 host_verifications: ['email', 'phone']
 host_has_profile_pic: t
 host_identity_verified: t
 neighbourhood: Neighborhood highlights
 neighbourhood_cleansed: Palais-Bourbon
 neighbourhood_group_cleansed: nan
 latitude: 48.84997
 longitude: 2.31974
 property_type: Entire rental unit
 room_type: Entire home/apt
 accommodates: 2
 bathrooms: nan
 bathrooms_text: 1 bath
 bedrooms: 1.0
 beds: nan
 amenities: ["Wifi", "Hot water", "Heating", "Coffee maker", "Kitchen", "Hair dryer", "Ethernet connection", "Dishes and silverware", "Iron", "Paid parking off premises", "Refrigerator", "Extra pillows and blankets", "Bed linens", "Oven", "Hangers", "Cooking basics", "Dryer", "Microwave", "Essentials", "Washer", "Shampoo"]
 price: nan
 minimum_nights: 2
 maximum_nights: 7
 minimum_minimum_nights: 2.0
 maximum_minimum_nights: 2.0
 minimum_maximum_nights: 7.0
 maximum_maximum_nights: 7.0
 minimum_nights_avg_ntm: 2.0
 maximum_nights_avg_ntm: 7.0
 calendar_updated: nan
 has_availability: t
 availability_30: 0
 availability_60: 0
 availability_90: 0
 availability_365: 0
 calendar_last_scraped: 2025-09-12
 number_of_reviews: 79
 number_of_reviews_ltm: 0
 number_of_reviews_l30d: 0
 availability_eoy: 0
 number_of_reviews_ly: 0
 estimated_occupancy_l365d: 0
 estimated_revenue_l365d: nan
 first_review: 2014-05-17
 last_review: 2020-03-13
 review_scores_rating: 4.78
 review_scores_accuracy: 4.94
 review_scores_cleanliness: 4.6
 review_scores_checkin: 4.91
 review_scores_communication: 4.94
 review_scores_location: 4.86
 review_scores_value: 4.73
 license: 7510702406383
 instant_bookable: f
 calculated_host_listings_count: 1
 calculated_host_listings_count_entire_homes: 1
 calculated_host_listings_count_private_rooms: 0
 calculated_host_listings_count_shared_rooms: 0
 reviews_per_month: 0.57

## 3. Exploration des Données 'reviews'

### 3.1 Aperçu Général du DataFrame `drive_reviews_df`

In [23]:
print('\nPremières 5 lignes :')
display(drive_reviews_df.head())
print('\nColonnes :')
print(drive_reviews_df.columns)
print('\nTaille (lignes, colonnes) :')
print(drive_reviews_df.shape)

Premières 5 lignes :

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,3109,207127433,2017-10-28,51636494,Patricia,Tout s'est bien déroulé. Merci bien. PG
1,3109,208779822,2017-11-03,4142888,Patricia,Un petit nid fouiller douillet situé dans app...
2,3109,295840159,2018-07-24,7415343,Laurent,"Appartement spacieux, propre,clair, et calme à..."
3,3109,553502638,2019-10-24,21159216,Anastasia,"Appartement totalement rénové, en parfait état..."
4,3109,1394813202239313560,2025-04-08,1030068,Silke,We had a wonderful stay at Anne's apartment. T...

Colonnes :
Index(['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments'], dtype='object')

Taille (lignes, colonnes) :
(2228691, 6)

### 3.2 Commentaires pour une Annonce Spécifique

In [24]:
# Définir l'ID de l'annonce à rechercher
listing_id_to_search = 2719440

# Filtrer le DataFrame drive_reviews_df pour l'ID d'annonce spécifié
comments_for_listing = drive_reviews_df[drive_reviews_df['listing_id'] == listing_id_to_search]

# Afficher les commentaires pour cette annonce
if not comments_for_listing.empty:
    print(f"Commentaires pour l'annonce {listing_id_to_search}:")
    for index, row in comments_for_listing.iterrows():
        print(f"- {row['comments']}")
else:
    print(f"Aucun commentaire trouvé pour l'annonce {listing_id_to_search}.")

Commentaires pour l'annonce 2719440:
- Appartement très bien situé, propre et bien équipée. Hôte très sympathique. Je recommande chaudement.
- Thibaut's apartment is in a great "locals" neighborhood, but easy walking distance to all the major attractions.  Two different subway lines have stops with a block.  We warned Thibaut we would be arriving at 7:30am after a series of long international flights, and he met us with coffee and pastries!  He was an excellent host.<br/>The apartment was clean and had a hair dryer available.  The shower was small, but not a problem.  We look forward to staying here again in the future!
- A really very nice flat very well located in Paris. The neighborhood is really calm. There are metro stations close to the flat which connect easily with the important buildings of Paris. The flat is very clean, with everything you need at your disposition. Thibaut is very friendly and very well disposed for everything you need. He text me before I arrive and after to make sure everything was allright. I love this flat and I look forward to going there again!!
<br/>Гуляли пешком до башни, минут 10-15 средний темп. До метро 2-3 минуты.
<br/>Thank you for the wonderful experience!
- Thibaut was a great host, he met us at the metro station and helped carry luggage to the apartment and he gave us a list of anything we would need in the area (supermarkets, bars, restaurants, etc).  The apartment was very nice, small but worked great.  It is in a great location, very close to the metro, although we walked to everything instead so you can pick which you'd rather do.
- Wir haben 4 Nächte bei Thibaut verbracht. Es ist eine kleine, nette Wohnung mit Super Lage. Die kleine Küchenzeile war für uns völlig ausreichend. Wir hatten eine tolle Zeit und würden jederzeit wieder kommen!
<br/>I would definitely recommend this place to all who are looking forward a trip to Paris.
- Квартира с отличным месторасположением (5 минут пешком до башни Монпарнасс - смотровая площадка, 15 минут до Эйфелевой башни). Рядом 2 магазина с продуктами и несколько булочных. Тибо оказался очень гостеприимным хозяином. Он встретил нас возле метро поздно ночью и помог с чемоданами. Его квартира очень чистая, создается впечатление, что живешь у старого доброго друга. Спасибо большое Тибо за его теплый прием!
- This was in a great location and Thibaut was extremely helpful! Our arrival was later then expected due to a delayed plane and delayed train but he waited for us and showed us around! It was a great experience and would definitely come back again!
- I was pleasantly surprised to find this flat had more space than I expected from the pictures. There was a separate room/area for just sitting, eating, etc. We didn't use the kitchen but appreciated the mini fridge and fridge availability. As stated in other reviews this is on the fifth floor with no elevator and the staircase is narrow, so be prepared! This place was very well located and not far from a metro station. The neighborhood also has great food options, a local market, fromagerie, charcuterie, boulangerie, cafe, etc. Would stay again!
<br/>Très bon accueil, logement très propre, Merci Tibo !
- Great location, great place!
<br/>I definitely wouldn't mind to stay in Thibaut' flat again if I ever go back to Paris again. I highly recommend it.
- It was a good location, very central. Thibaut was always in contact if we needed anything. would definitely recommend it!
- Appartement propre, confortable et très bien situé, hôte disponible, je recommande !
<br/>Thank you so much!
<br/>Autre point important: le canapé-lit est  confortable et nous avons très bien dormi.
- Great apartment! Clean and friendly. Host very helpful and kind! Recommended for anyone who wants to spend a wonderful time in Paris! TOP !!!
- Thank you Tibo for your hospitality. Everything looked the same as described and was in very good condition. The location is great and give you a chance to explore the city even walking. Thank you that you agreed to check in at 10.30 pm very late due to our flight. For sure I will come one day to Paris again and if the apartment is still  available, I will rent it again.
- Appartment is very lovely and 50 m from metro and supermarket. Has everything you need near by. We have been around whole Paris with no problems and even walked till from Notra Dame till home since it was  45 min walk . We enjoyed Latin quarter and Luxemburg Gardens on the way.
- Esperienza bellissima! Thibo è stato gentilissimo e disponibile.. La casa è comoda per la metro è vicina ad ogni attrattiva che la città offre. Le foto rispecchiano perfettamente la realtà. Consiglio a tutti l'appartamento !
- 5ème étage sans ascenseur rend montrer les valises un peu difficilement. Mais c'est un très joli appartement et bien situé.
- The flat is exactly as described and shown in the pictures. It's a lovely little place to stay. Thibaut was very helpful in giving us great instructions to get there and letting us leave our things there late on the day we checked out so that we could explore Paris without our bags. It was a great experience and I'd highly recommend it. There's some nice bakeries in the area and a Carrefour very close, and good transport links. We walked to the Eiffel tower and the Catacombs.
<br/>I completely recommend this apartment if you want to have a good stay in Paris.
- Tibo was a great host and his place was perfect for my husband and me. Great location and very close to the metro. Lots of good restaurants and bakeries in the area. Plus, a grocery store is just around the corner. Great trip and we really enjoyed our stay.
- Thibaut apartment was the perfect "base camp" for our trip in París. It is very well situated, 1 minute walking from train station, so you can get everywhere very easily. The apartment is in a very quite street, and you have a supermarket round the corner. The apartment is clean and with all the facilities. And Thibaut is a nice guy! <br/>We'll repeat when we come back to Paris. Too much to see!
<br/>
- Excellent location. Two blocks from the metro, but also we were able to walk to all attractions. <br/>Two markets, a bank and many cafes/bars within a two minute walk. <br/>Communication and key exchange was perfect.
- Nice flat, close to city center with good connection. The only problem was with communication with our host. First when we want to check-in - we had to sent request to AirBnB support and second when we want to check-out. To be honest, he didn't come at all. As i said, flat was really nice, but these things made it bad.
- La casa de Thibaut es exactamente como se describe en su perfil: muy cerca del centro, con muchos detalles y muy acogedora. La comunicación con él fue genial desde el principio y nos recomendó lugares deliciosos. ¡Repetiremos!
- Bonne communication et très bon accueil. Le mobilier de l’appartement a changé depuis les photos mais sans que cela présente de difficultés. Précision, il n’y a pas de tv mais le wifi fonctionne très bien. Lit très confortable, appartement agréable pour un séjour de qqes jours.
- El apartamento esta bien,  tal como se ve en las fotos ideal para una pareja, el metro esta a 3 minutos y hay dos supermercados muy cerca también recomendable 👍
- Séjour agréable dans un appart fonctionnel, dans une rue tranquille.<br/>Hôte très accueillant et attentif à ce que tout se passe bien.
- Thibo é uma pessoa que fica a disposição durante a sua permanência e sempre responde as dúvidas. Viajamos eu, minha esposa e a minha filha de 1 ano, realmente as escadas foram um tanto quanto incômodas, não aconselho para casais com filhos. Para um casal sem filhos ou um viajante sozinho, o apartamento é ok. Destaque para a localização e proximidades a mercados e padarias. Escolha a padaria que se chama Secco, BEM MELHOR que a outra.
- Tibo siempre estuvo pendiente de nuestra llegada, estancia y salida. el departamento esta céntrico y hay un super y dos estaciones de metro a menos de 5 minutos caminando. El ddepartamento esta tal cual se muestra en las fotos. limpio y con artículos de uso personal<br/>
- Great location, comfortable bed, and a good shower! If you go to bed early, you may be bothered by the restaurants down the road. Tibo left the place very clean for us and was very helpful with anything we asked of him. The apartment is very close to public transportation to get you anywhere you need to go during your stay.
- Good location and clean
- It's a very nice, clean flat at the city centre. There is no lift, but if you don't mind climbing some stairs (which my husband and I didn't at all), then it's the perfect place for a holiday in Paris!
- Beautiful, cute flat in a great location. Tibo was very quick with responding to queries and it was perfect for our stay.
- We liked the apartment, it is light, with a separate bedroom and a large bed. Good area, up to the eiffel tower we reached in 15 minutes, quiet area, there are cafes and shops, on the first floor laundry. I would like to note that the apartment is cozy, the furniture is in good condition, everything you need and even more for living there. The windows overlook the two sides, the sun was falling into the bedroom in the morning. There were no problems in communicating with the host, a nice young man. unfortunately, we were not able to see each other. I recommend this apartment and the owner!
- As someone who has formerly lived in Paris, I felt like Thibaut's flat was pretty much perfect. Great, central, non-touristy location with multiple metro lines nearby. His flat was clean and quiet with authentic French touches. And as a host, Thibaut was also very kind and considerate. Completely recommended.
- Tibo’s place was a great location for anyone traveling for the first time. Close to the metro stations, and walking distance from
- Great location, within 1 1/2 miles to Eiffel Tower, Louvre, Nôtre Dame, St Chapelle and 1 mile to Musée d’Orsay and Luxemburg gardens. You can run at Luxemburg or the other direction near Arme Museum. Great grocery nearby and metro and bus stop right there. It’s perfect for two people but that’s all, couch is small loveseat. There is a hair dryer and Tibo provides an electrical converter, but the laundry is a separate facility next door..We liked the refrigerator and used the oven to heat up meals...and the wine glasses and cork screw! We never met Tibo but he replied to our emails quickly and we were able to get into the unit easily with his directions.
- I really suggest staying​ here! The location is perfect, in the centre with a very close metro! The apartment is clean and you can find everything you need. Thibaut was very polite and friendly with us!
- Tibo’s flat was just as pictured and described. It’s pretty spacious in my opinion and he was a great host. The apartment was conveniently located and easy to get to and from major attractions. I would recommend!
- Gran anfitrión todo como lo esperábamos !! Seguro volveremos !!
- The flat was lovely and just a couple steps away from a great French restaurant. It was easy to walk to most of central Paris. The lights to the flat were supposed to be automatic, however they never turned on for us and we had to use our phones to light the stairway. I also wasn't expected nearly that many stairs and in such a tight space too. However that didn't take away from how cozy and comfy the flat was, and how absolutely beautiful Paris was!
- Very nice apartment in a convenient area near metro and supermarkets. Thibaut replies in good time and has a lovely apartment. Would stay here again
- Tibo's place is stylish, Parisian and has everything you need for a stay in Paris. The location of the apartment is perfect for exploring beautiful Paris and is a short walk from the Metro Station. Tibo provided great communication and local tips.  The apartment was cosy and warm even in January. The stairs were not a problem for us but they are steep!
- Tibo’s place is lovely and in a fantastic location. Perfect for two. He is super helpful and quick to respond to any questions. The bedroom is spacious and the living room/kitchen cosy. The apartment is on the 4th floor so if you have heavy bags, just make sure you have someone to help you. I stayed at Tibo’s with a friend for a weekend and we had a great time. Tibo’s recommendations for restaurants are worth the visit!
- Thibault was a great host, really easy to get hold of and make arrangements with! The flat was great for our weekend in Paris, especially the location! We had the best time!
- Nous sommes très satisfaits de notre séjour dans l'appartement de Thibaut. Il est bien situé, très propre, confortable et bien décoré. Merci pour les conseils de restaurants et bars!  On recommande fortement
- Appartement idéalement placé, à 2 pas de la grande épicerie de Paris et de petits commerçants de quartier. Le quartier est vraiment très sympa avec de nombreuses boulangeries à proximité dont une de Cyril Lignac (les viennoiseries sont tellement bonnes!!). Très bien desservi par le métro. Chambre très calme.
- A very fine upper floor apartment in the middle of the city. With luck, even a parking lot in front of the house.
- Tibo is super nice and friendly host. He will provide you with the welcome kit that has all the information you need to get into the flat, and some great places to try in Paris. The flat is cozy, quite, and exactly how it looks in the pictures. The location of the flat is great. I would definitely go there again.
- Really nice apartment in a great area in Paris! Lots of things to do within walking radius
- Great apartment in an amazing location! Would recommend
- In my opinion that was the best location. Close to the metro station. Close to almost all most popular attractions. Very clean flat and very easy communication with Tibo. <br/>Our stay in Tibo's flat was perfect. <br/>Thank you so much 😊
- Está muy bien ubicado, limpio y tiene una cama donde se descansa bien
- Great communication, great host. Thibaut welcomed us well in advance with a “bienvenue à paris” package which gave us easy to follow instructions on getting to the apartment from the airport, the best metro station, cool bars and cafes and great tips for sightseeing! The apartment was perfect for two people, we loved that there is a supermarket so close as well! Bed was heaps comfy and amentites were good.<br/>Only downside was there was no airconditioning and no fan to compensate. We thoroughly enjoyed our stay here☺️
- We loved our stay - the flat was ideal for all out needs!
- Amazing location! Tibo was a great host and replied really fast to any questions you had. Would definitely recommend staying here 😁
- It’s nice, clean, really close to the metro and cool places. Loved the kit the host gave me with info about basically, everything about Paris.
- Great location close to metro. Place is just like it is described. Tibo was very easy to communicate with, and he sent us a welcome kit with lots of tips. I would recommend.
- We had a nice stay at Thibaut’s place<br/>The location is excellent. The neighborhood is fantastic and Metro is right nearby. <br/>Communication with Thibaut was clear and quick and his welcome package was very helpful. <br/>Highly recommended.
- Was such a great location to be able to walk to most of the main tourist attractions, metro easy walking distance as well as local grocery stores. We would recommend this place and stay here again next time we are in Paris.
- Flat in a great location for metro and supermarket. Nice local shops nearby. Bit of a climb to reach it but has everything you need and was very quiet
- Fantastic location, quiet yet walking distance to many attractions (Eiffel Tower, Des Invalides, Musee Rodin, Musee D'Orsay, Jardins de Luxembourg, etc). A wonderful bakery a few doors down, a Carrefour for groceries, laundry facilities right next door, great cafes nearby. The flat is great for two people, plenty of space, good kitchen, nice bath. Thibaut was a kind, communicative, generous host, we hope to return one day. Thank you, Thibaut!
- Thibaut’s place is absolutely amazing. It’s located in the centre, near almost famous landscapes. Thibaut was super nice. He responded to our queries quickly and helped to book a taxi to the airport at very early morning. 100% recommend to other hosts.
- Great apartment, fairly small so I would recommend for one person rather than two. The location is good also as near metro station which takes about 25min from Gard Du Nord.
- Super séjour ! Exactement ce dont j’avais besoin ! Merci Thibaut de l’accueil et de la réactivité !
- Appartement sympa, super bien situé, au calme et impeccable
- Great location in central Paris, very clean and stylish apartment. Highly recommend.
- Great place for a couple's break (if you're prepared to climb four flights of stairs!) Hospitable/helpful host and well stocked flat. Good location near to Metro stations. Perfect for a few nights in Paris :)
- Adresse parfaite.<br/>Appartement bien placé,  calme, correctement équipé et très propre.
- Location was fantastic. Close to subway and a luxury department store. Residence area is adjacent so several big supermarkets around the house. However no a lift in the building so think twice if you are traveling with a senior or carrying heavy luggage. Overall great!!!!
- Thibaut was a great host. He communicated well, accommodated our early and late check in/check out and even developed a welcome kit for guests! His apartment is well situated for exploring some of Paris' popular areas of interest.  The neighborhood itself is quaint and makes you feel as if you are Parisien too. Would definitely recommend to others and hope to return one day!
- Excelente ubicación, cerca de la zona buenos restaurantes, a 2 min el metro, cerca de lavandería y carrefour.

## 4. Analyse des Quartiers

### 4.1 Liste des Quartiers Disponibles (`neighbourhood_cleansed`)

In [25]:
# Obtenir toutes les valeurs uniques de la colonne 'neighbourhood_cleansed'
unique_neighbourhoods = drive_listings_df['neighbourhood_cleansed'].unique()

# Afficher la liste des quartiers uniques
print("Liste des 'neighbourhood_cleansed' uniques:")
for neighbourhood in unique_neighbourhoods:
    print(f"- {neighbourhood}")

Liste des 'neighbourhood_cleansed' uniques:
- Palais-Bourbon
- Hôtel-de-Ville
- Batignolles-Monceau
- Opéra
- Buttes-Montmartre
- Louvre
- Panthéon
- Entrepôt
- Ménilmontant
- Bourse
- Vaugirard
- Luxembourg
- Temple
- Popincourt
- Passy
- Buttes-Chaumont
- Gobelins
- Observatoire
- Reuilly
- Élysée

### 4.2 Comptage des Annonces dans un Quartier Spécifique (Exemple : 'Élysée')

Note : L'exécution précédente de ce code a renvoyé 0, car 'Élysée' n'est pas une valeur exacte dans la colonne `neighbourhood_cleansed`. La liste ci-dessus montre les noms exacts des quartiers disponibles.

In [28]:
# Filtrer le DataFrame pour les annonces dans 'Le Élysée' en utilisant 'neighbourhood_cleansed'
e_listings = drive_listings_df[drive_listings_df['neighbourhood_cleansed'] == 'Élysée']

# Compter le nombre d'annonces
num_e_listings = len(e_listings)

print(f"Nombre d'éléments situés dans le Marais: {num_e_listings}")

Nombre d'éléments situés dans le Marais: 2625